project:
  type: website

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Services"
        menu:
          - text: "Supervision & Compliance"
            href: services/supervision.qmd
          - text: "Government Consulting"
            href: services/consulting.qmd
          - text: "Research & Analysis"
            href: services/research.qmd
      - text: "Contact"
        href: contact.qmd
    right:  # Aligned with `left:`
      - text: "English"
        id: "lang-en"
        href: "#"
      - text: "Español"
        id: "lang-es"
        href: "#"
     
format:
  html:
    css: styles.css
    include-after-body: language-toggle.js


    
    


